### ISSUE TITLE
feat: support for highlight a "Note" and "Warning" using blockquote

### ISSUE THREAD

**Issue by egel** [immanelg/mdopen#10]
Hello!

I'm writing here as a possible new idea/feature to be considered

I noticed that the GitHub markdown supports highlighting blockquotes with specific prefixes like `[!NOTE]` or `[!TIP]` and rendering this differently.

https://github.com/orgs/community/discussions/16925

Do you think would be possible to add a similar styling feature to have more immersive behavior to the GitHub pages?

BTW great work! I really enjoy using this markdown previewer before I push things to repo!

**Comment by immanelg** [comment]
I don't think [markdown-rs](https://docs.rs/markdown/1.0.0-alpha.21/markdown/struct.Options.html) supports that, but I wanted to migrate to pulldown-cmark which [does](https://github.com/pulldown-cmark/pulldown-cmark/issues/718). Pulldown-cmark will also allow us to have links in headers and generating table of contents.
