### ISSUE TITLE
Add support for CORS

### ISSUE THREAD

**Issue by egel** [immanelg/mdopen#9]
First of all, thank you so much for this amazing program. Using it locally works like a charm!

Here I just wanted you to consider adding some support for CORS, especially for cases when using images from other domains (e.g. like the picture I tried to test that comes outside of origin)

- Browser: Brave Version 1.68.141 Chromium: 127.0.6533.120 (Official Build) (arm64)
- OS: macOS Sonoma 14.6.1

Screenshot

![image](https://github.com/user-attachments/assets/0790360a-7f01-4a10-994d-7cfb0bff3455)

Thanks again!

Best,
Maciej

**Comment by immanelg** [comment]
Hello, thanks for reporting! I tested with imgur, it seems to prohibit CORS (I don't think you can change that?). For some weird reason, if I change 127.0.0.1 to localhost, the imgur image loads. 
Images from other websites like raw.githubusercontent.com seem to work (on my machine). Maybe that's an issue specifically with imgur?

**Comment by egel** [comment]
Yeah, I've checked and this is probably not a problem with the `mdopen` itself.

I did a small, quick research around the topic, and this is likely an effect of recent changes in the browsers that raise restrictions around access to resources outside of the domain (i.e.: Chrome [Edge, Brave], FF, ...)

- while using `127.0.0.1:5032` to render images correctly, I had to additionally specify [`referrerpolicy="no-referrer"`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) to each image outside the domain.
- when using `localhost:5032` this problem does not exist

> A while ago I stumbled upon exactly the same problem (with `localhost` and `127.0.0.1`), although I did not find any clear explanation for this behavior.
> My best guess here would be that usually, `localhost` is usually by default defined to `/etc/hosts`, and this somehow lowers the default referer/access policy.

> [!TIP]
> My small suggestion that you may consider 
> 
> If we would use `localhost:<PORT>` instead of `127.0.0.1:<PORT>` - This could significantly improve the default user experience, especially for local development.
> 
> Also by defaulting to `localhost`, you're making it easier for users to remember and type URLs. This is a great step forward in reducing errors and typos.

**Comment by immanelg** [comment]
Does using localhost close this issue (or we can do better)?

**Comment by egel** [comment]
yes, it does to me. Thanks @immanelg !

ps. Sorry for the late response, I was quite busy in the last couple of days.
